"""Added status field in Habit Comletion table

Revision ID: 024dba85c56a
Revises: 7b1b1786fde8
Create Date: 2025-05-03 23:37:43.038834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024dba85c56a'
down_revision: Union[str, None] = '7b1b1786fde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habitcompletion', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habitcompletion', 'status')
    # ### end Alembic commands ###
