"""Make is_admin a real column

Revision ID: 046660e97f9b
Revises: dd32c01b1cc8
Create Date: 2025-05-06 00:56:08.712437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046660e97f9b'
down_revision: Union[str, None] = 'dd32c01b1cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with default=True (or False) temporarily
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))

    # If you want to remove the server_default after setting values:
    op.alter_column('user', 'is_admin', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
