"""Added auto increment for user id

Revision ID: 22e6930cea56
Revises: 36d54aaec735
Create Date: 2025-05-05 01:30:33.354844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e6930cea56'
down_revision: Union[str, None] = '36d54aaec735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the foreign key constraint first
    op.execute('ALTER TABLE habit DROP CONSTRAINT habit_user_id_fkey')
    
    # Now drop the unique constraint
    op.execute('ALTER TABLE "user" DROP CONSTRAINT user_id_key')

    # Optionally, add auto increment or any other required changes
    op.alter_column('user', 'id', server_default=None, autoincrement=True)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_id_key', 'user', ['id'])
    # ### end Alembic commands ###
