"""Initial migration

Revision ID: 734604bac8ac
Revises: 
Create Date: 2025-05-08 17:45:08.927468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import String


# revision identifiers, used by Alembic.
revision: str = '734604bac8ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', String(), nullable=False),
    sa.Column('email', String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit',
    sa.Column('name', String(), nullable=False),
    sa.Column('description', String(), nullable=True),
    sa.Column('category', sa.Enum('PERSONAL_DEVELOPMENT', 'FITNESS', 'FINANCE', 'NUTRITION', 'SOCIAL', 'HOME_AND_ORGANIZATION', 'SELF_CARE', 'MENTAL_WELLNESS', 'GENERAL', name='category'), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habitcompletion',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habitcompletion')
    op.drop_table('habit')
    op.drop_table('user')
    # ### end Alembic commands ###
