"""Changed hashed_password column name to password in User table

Revision ID: a86b0333d2ae
Revises: cdefa69a4624
Create Date: 2025-05-05 01:06:01.403456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import String


# revision identifiers, used by Alembic.
revision: str = 'a86b0333d2ae'
down_revision: Union[str, None] = 'cdefa69a4624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', String(), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
