"""Add user model and related routes

Revision ID: cdefa69a4624
Revises: 024dba85c56a
Create Date: 2025-05-04 20:03:55.171801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import String


# revision identifiers, used by Alembic.
revision: str = 'cdefa69a4624'
down_revision: Union[str, None] = '024dba85c56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', String(), nullable=False),
    sa.Column('hashed_password', String(), nullable=False),
    sa.Column('email', String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('username', 'id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('habit', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'habit', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.drop_column('habit', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
