"""fix auto-increment for user id

Revision ID: dd32c01b1cc8
Revises: 22e6930cea56
Create Date: 2025-05-05 01:41:27.876581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd32c01b1cc8'
down_revision: Union[str, None] = '22e6930cea56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'habit', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit', type_='foreignkey')
    # ### end Alembic commands ###
